services:
  lawyers-and-clients:
    image: "elvisea/lawyers-and-clients:latest"  # Valor fixo conforme solicitado
    container_name: lawyers-and-clients
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]
