services:
  lawyers-and-clients:
    image: "elvisea/lawyers-and-clients:latest"  # Valor fixo
    container_name: lawyers-and-clients
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "start"]
    networks:
      - lawyers_and_clients_network  # Nome da rede que foi criada (deve bater com os outros arquivos)

networks:
  lawyers_and_clients_network:
    external: true  # Usando a rede externa criada
    name: lawyers_and_clients_network  # O nome da rede deve ser o mesmo em todos os arquivos
