import { Errors } from "@/types";

export const errors: Errors = {
  UNKNOWN_ERROR: {
    title: "UNKNOWN_ERROR_TITLE",
    description: "UNKNOWN_ERROR_DESCRIPTION",
  },

  TOKEN_EXPIRED: {
    title: "TOKEN_EXPIRED_TITLE",
    description: "TOKEN_EXPIRED_DESCRIPTION",
  },

  TOKEN_NOT_FOUND: {
    title: "TOKEN_NOT_FOUND_TITLE",
    description: "TOKEN_NOT_FOUND_DESCRIPTION",
  },

  TOKEN_ALREADY_USED: {
    title: "TOKEN_ALREADY_USED_TITLE",
    description: "TOKEN_ALREADY_USED_DESCRIPTION",
  },

  EMAIL_VERIFICATION_REGISTER_NOT_FOUND: {
    title: "EMAIL_VERIFICATION_REGISTER_NOT_FOUND_TITLE",
    description: "EMAIL_VERIFICATION_REGISTER_NOT_FOUND_DESCRIPTION",
  },

  EMAIL_ALREADY_VERIFIED: {
    title: "EMAIL_ALREADY_VERIFIED_TITLE",
    description: "EMAIL_ALREADY_VERIFIED_DESCRIPTION",
  },

  USER_NOT_FOUND: {
    title: "USER_NOT_FOUND_TITLE",
    description: "USER_NOT_FOUND_DESCRIPTION",
  },

  USER_ALREADY_EXISTS: {
    title: "USER_ALREADY_EXISTS_TITLE",
    description: "USER_ALREADY_EXISTS_DESCRIPTION",
  },

  EMAIL_NOT_VERIFIED: {
    title: "EMAIL_NOT_VERIFIED_TITLE",
    description: "EMAIL_NOT_VERIFIED_DESCRIPTION",
  },

  INVALID_CREDENTIALS: {
    title: "INVALID_CREDENTIALS_TITLE",
    description: "INVALID_CREDENTIALS_DESCRIPTION",
  },

  EMAIL_ALREADY_EXISTS_NOT_VERIFIED: {
    title: "EMAIL_ALREADY_EXISTS_NOT_VERIFIED_TITLE",
    description: "EMAIL_ALREADY_EXISTS_NOT_VERIFIED_DESCRIPTION",
  },

  EMAIL_ALREADY_EXISTS_VERIFIED: {
    title: "EMAIL_ALREADY_EXISTS_VERIFIED_TITLE",
    description: "EMAIL_ALREADY_EXISTS_VERIFIED_DESCRIPTION",
  },

  PHONE_ESTABLISHMENT_ALREADY_EXISTS: {
    title: "PHONE_ESTABLISHMENT_ALREADY_EXISTS_TITLE",
    description: "PHONE_ESTABLISHMENT_ALREADY_EXISTS_DESCRIPTION"
  },

  INVALID_EMAIL_OR_PASSWORD: {
    title: "INVALID_EMAIL_OR_PASSWORD_TITLE",
    description: "INVALID_EMAIL_OR_PASSWORD_DESCRIPTION"
  },
};
